FROM node:23-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --production
COPY main.js ./

ARG MQTT_URI
ENV MQTT_URI=$MQTT_URI

ARG MQTT_PREFIX
ENV MQTT_PREFIX=$MQTT_PREFIX

ARG MQTT_SUBSCRIPTIONS
ENV MQTT_SUBSCRIPTIONS=$MQTT_SUBSCRIPTIONS

ARG HTTP_PORT
ENV HTTP_PORT=$HTTP_PORT

ARG SERVICE_CONFIG
ENV SERVICE_CONFIG=$SERVICE_CONFIG

CMD ["node", "/app/main.js"]
